version: "2"
services:
  mysql:
    build: ./mysql
    container_name: "mysql"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /server/mysql/data:/var/lib/mysql
      - /server/mysql/conf/mysql:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    build: ./redis
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /server/redis:/data
      - /server/redis/conf:/etc/redis
  memcached:
    build: ./memcached
    container_name: "memcached"
    restart: always
    ports:
      - "11211:11211"
    environment:
      TZ: "Asia/Shanghai"
  php:
    build: ./php
    container_name: "php"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /server/www:/var/www/html
      - /server/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - "mysql"
      - "redis"
      - "memcached"
  nginx:
    build: ./nginx
    container_name: "nginx"
    restart: always
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /server/www:/usr/share/nginx/html
      - /server/nginx:/etc/nginx
      - /server/logs/nginx.logs:/var/log/nginx
